"use strict";

globalThis.MATCH_SESSION_SPLASH_QUOTES = Object.freeze([
  {
    id: "daigo-one-step-stronger",
    originalLanguage: "ja",
    original: "1日ひとつだけ、強くなる。",
    translation: "Get just a little stronger each day.",
    player: "Daigo Umehara",
    source: "1日ひとつだけ、強くなる。",
    sourceUrl: "https://www.famitsu.com/news/201507/15083164.html",
  },
  {
    id: "tokido-fighting-game-great",
    originalLanguage: "en",
    original: "Fighting game is something so great!",
    translation: "格闘ゲームって、本当に素晴らしい！",
    player: "Tokido",
    source: "EVO 2017 winner interview",
    sourceUrl: "https://www.youtube.com/watch?v=3tN0zi8eino",
  },
  {
    id: "alex-valle-aggressive",
    originalLanguage: "en",
    original: "Being aggressive opens doors.",
    translation: "積極的に攻めることで、活路が開ける。",
    player: "Alex Valle",
    source: "EVO player retrospective",
    sourceUrl: "https://evo.gg/news/how-alex-valle-rushed-his-way-to-the-hall-of-fame/",
  },
  {
    id: "angrybird-confident",
    originalLanguage: "en",
    original: "When I qualified for the top six, I was confident that I would win.",
    translation: "トップ6進出が決まった時、自分が優勝すると確信していた。",
    player: "AngryBird",
    source: "EVO 2023 winner interview",
    sourceUrl: "https://www.thenationalnews.com/arts-culture/2023/09/01/angrybird-abu-dhabi-gamer-champion-evo/",
  },
  {
    id: "menard-competitive-torture",
    originalLanguage: "en",
    original: "The game is extremely fun, but competitively it's torture.",
    translation: "このゲームはめちゃくちゃ楽しい。でも競技としては拷問だ。",
    player: "MenaRD",
    source: "Trash Talk interview",
    sourceUrl: "https://www.youtube.com/watch?v=j-zvcoL5L5o",
  },
  {
    id: "menard-waiting-for-win",
    originalLanguage: "en",
    original: "Inside, I was very quiet, very neutral and just waiting for the win to celebrate.",
    translation: "心の中ではとても静かで、ただ勝って祝う瞬間を待っていた。",
    player: "MenaRD",
    source: "EVO 2025 winner interview",
    sourceUrl: "https://www.dexerto.com/esports/menard-explains-the-mindset-of-a-champion-after-winning-evo-2025-3233961/",
  },
  {
    id: "punk-care-about-myself",
    originalLanguage: "en",
    original: "I only really care about myself.",
    translation: "正直、自分のことしか気にしていない。",
    player: "Punk",
    source: "EVO 2024 winner interview",
    sourceUrl: "https://www.dexerto.com/esports/punks-emotional-evo-victory-was-seven-years-in-the-making-but-its-just-the-start-2834062/",
  },
  {
    id: "punk-win-money",
    originalLanguage: "en",
    original: "I want to win a lot of money.",
    translation: "たくさん賞金を勝ち取りたい。",
    player: "Punk",
    source: "EVO 2024 winner interview",
    sourceUrl: "https://www.dexerto.com/esports/punks-emotional-evo-victory-was-seven-years-in-the-making-but-its-just-the-start-2834062/",
  },
  {
    id: "sanford-pick-top-tier",
    originalLanguage: "en",
    original: "Pick a top tier.",
    translation: "強キャラを選べ。",
    player: "Sanford Kelly",
    source: "2009 Chinatown Fair video retrospective",
    sourceUrl: "https://evo.gg/news/how-sanford-kelly-became-central-to-the-story-of-marvel-vs-capcom-2",
  },
  {
    id: "sanford-money-work-for-me",
    originalLanguage: "en",
    original: "I want the money to work for me. I'm tired of working for the money.",
    translation: "金に働いてもらいたい。金のために働くのはもう疲れた。",
    player: "Sanford Kelly",
    source: "2009 Chinatown Fair video retrospective",
    sourceUrl: "https://evo.gg/news/how-sanford-kelly-became-central-to-the-story-of-marvel-vs-capcom-2",
  },
  {
    id: "latif-best-by-far",
    originalLanguage: "en",
    original: "I am the best at this game by FAR.",
    translation: "このゲームでは、俺が圧倒的に一番だ。",
    player: "Latif",
    source: "Post-tournament social media post",
    sourceUrl: "https://knowyourmeme.com/memes/i-dont-care-what-anybody-says-or-think-i-am-the-best-at-this-game-by-far",
  },
  {
    id: "smug-command-grabbed",
    originalLanguage: "en",
    original: "Acting like you won't get command grabbed!",
    translation: "コマ投げされないつもりでいるな！",
    player: "Smug",
    source: "Recurring stream catchphrase",
    sourceUrl: "https://www.reddit.com/r/StreetFighter/comments/l1fvt2/",
  },
  {
    id: "filipino-champ-you-are-free",
    originalLanguage: "en",
    original: "You are free.",
    translation: "お前は楽勝だ。",
    player: "Filipino Champ",
    source: "Winter Brawl X player callout",
    sourceUrl: "https://www.espn.com/esports/story/_/id/15553688/filipino-champ-panda-global-renew-sponsorship-deal-2016",
  },
  {
    id: "sonicfox-talk-and-win",
    originalLanguage: "en",
    original: "I do what I need to do, I talk my shit, and I win.",
    translation: "やるべきことをやって、言いたいことを言って、そして勝つ。",
    player: "SonicFox",
    source: "ESPN player interview",
    sourceUrl: "https://www.espn.com/gaming/story/_/id/21174282/for-dominque-sonicfox-mcclean-confidence-weapon",
  },
  {
    id: "angrybird-secret-practice",
    originalLanguage: "en",
    original: "I started practising without telling him. Then he came over and I destroyed him.",
    translation: "彼には黙って練習を始めた。それから彼が遊びに来て、ボコボコにした。",
    player: "AngryBird",
    source: "The National player interview",
    sourceUrl: "https://www.thenationalnews.com/arts-culture/2023/09/01/angrybird-abu-dhabi-gamer-champion-evo/",
  },
  {
    id: "justin-wong-learn-today",
    originalLanguage: "en",
    original: "We gon' learn today!",
    translation: "今日は学んでもらうぞ！",
    player: "Justin Wong",
    source: "Paramount Games interview",
    sourceUrl: "https://www.paramountgames.com/editorial/justin-wong-for-avatar-legends",
  },
  {
    id: "kakeru-undisputed-best",
    originalLanguage: "ja",
    original: "自他共に認められる「最強」を目指したい",
    translation: "I want to become the undisputed best.",
    player: "Kakeru",
    source: "GAME Watch interview",
    sourceUrl: "https://game.watch.impress.co.jp/docs/interview/2011054.html",
  },
]);
